### ISSUE TITLE
Complete the c++ program to generate fibonacci triangle 

### ISSUE THREAD

**Issue by Freak29** [Freak29/Basic-C-#28]
File is fibonaccitriangle.CPP
![Screenshot (256)](https://user-images.githubusercontent.com/72217338/135744898-2e490445-4317-4f32-a2c7-330186344c48.png)

**Comment by Alankruthisaieni** [comment]
Hey please assign it to me

**Comment by Alankruthisaieni** [comment]
Done Sir Once check it

**Comment by Alankruthisaieni** [comment]
PR Fibonacci #32

**Comment by rakeshbodavula** [comment]
can i work on it?

**Comment by Freak29** [comment]
@rakeshbodavula issue is closed now
